//! Pure domain model for the cloud provider simulator.
//!
//! This crate deliberately has no dependency on Bevy, egui, SQLite or threads.

pub mod cabling;
pub mod command;
pub mod completion;
pub mod device;
mod equipment_config;
pub mod error;
pub mod event;
pub mod ids;
pub mod ios;
pub mod ip_allocation;
pub mod link;
pub mod localized_text;
pub mod network;
pub mod network_outlet;
pub mod optics;
pub mod port;
pub mod power;
pub mod provider;
pub mod rack;
pub mod remote;
pub mod resources;
pub mod router_hardware;
pub mod server_hardware;
pub mod server_os;
pub mod shop;
mod shop_compatibility;
pub mod storage;
pub mod switching;
pub mod terminal;
pub mod world;

pub use cabling::*;
pub use command::*;
pub use completion::*;
pub use device::*;
pub use error::*;
pub use event::*;
pub use ids::*;
pub use ios::*;
pub use ip_allocation::*;
pub use link::*;
pub use localized_text::*;
pub use network::*;
pub use network_outlet::*;
pub use optics::*;
pub use port::*;
pub use power::*;
pub use provider::*;
pub use rack::*;
pub use remote::*;
pub use resources::*;
pub use router_hardware::*;
pub use server_hardware::*;
pub use server_os::*;
pub use shop::*;
pub use storage::*;
pub use switching::*;
pub use terminal::*;
pub use world::*;
